[metadata]
    version    = 2
    data_class = "AD:LUXSOLIS:xv/fx"
    signoff    = "core mensam crinitus furrure ad metadata"
    arch       = "EXSTRUCTA DOCUMENTUM"

[changelog-extras]
[changelog-extras.common]
    early_access_header = "our Patreon!"
    early_access_url    = "https://patreon.com/hentaiOS"
    community_discuss   = "https://t.me/hentaiOSchat"

[changelog-extras.common.dogfood-discuss]
    header         = "dogfood-feedback@"
    data           = "3zDxR41CjuOjKAKizCVdQtPcgPfYS5ywCSaK3xwLhdyxfkmDlvee8cpkDT82KQ8PG0_CqWedG7bFmeurWB9Mi8DIt-lnB9MpNoLVK_0xGXS4v-ss"
    data_encrypted = true

[changelog-extras.common.dogfood-info]
    header         = "go/operators"
    data           = "R0jqhqIDux8yDtKVQDEKD4Shgslziq2Zb0aq6v2ZNNIBrFqzr5WEPp0"
    data_encrypted = true
