[metadata]
    version    = 2
    data_class = "AD:LUXSOLIS:xv/fx"
    signoff    = "core mensam crinitus furrure ad metadata"
    arch       = "EXSTRUCTA DOCUMENTUM"

[changelog-extras]
[changelog-extras.common]
    early_access_header    = "our Patreon!"
    early_access_url       = "https://patreon.com/hentaiOS"
    community_discuss      = "https://t.me/hentaiOSchat"
    dogfood_discuss_header = "dogfood-feedback@"
    dogfood_info           = "go/biteof87"

[changelog-extras.common.dogfood-discuss]
    header         = "dogfood-feedback@"
    data           = "xFs6haRbvDLA5qGnyjnakmOrjjFKybno4jAPizRdwNKs0eDBtWzCYTIsqCZrx4gI1dBYaC7FDUusiQx1kLp9QXs3mFXynhzmA84cPmbr1Bu-76AL0SxpzlioYUKk"
    data_encrypted = true

[changelog-extras.common.dogfood-info]
    header         = "go/operators"
    data           = "15xwUuvkXJZ0qYnF-FBdsLmyvBmr6W2GnnViIME_e0-JS851xf1VEDYl"
    data_encrypted = true
