#:schema ./schema/changelogDataSchema.jsonc
[metadata]
    version    = 2
    data_class = "AD:LUXSOLIS:xv/fx"
    signoff    = "core mensam crinitus furrure ad metadata"
    arch       = "EXSTRUCTA DOCUMENTUM"

[changelog]
[changelog.tag.luxsolis]
    file = "incommutabilis"

[changelog.tag."UP1A.230905.019"]
    file = "ursamoon-early-dogfood"

[changelog.tag."UP1A.231005.007"]
    file = "ursamoon"

[changelog.tag."AP3A.240905.015.A2"]
    file = "vallhound"

[changelog.device]
[changelog.device.luxsolis]
    file = "incommutabilis"
